# Introducción a la Programación para Ciencia de Datos
## Lenguaje de programación R
_Rocío Romero Zaliz_ - rocio@decsai.ugr.es

# Tipos de datos básicos

* numeric / integer
* logical
* complex
* character

In [21]:
1

[1] 1

In [22]:
print(1)

[1] 1


In [23]:
class(1)

[1] "numeric"

In [24]:
class(1.5)

[1] "numeric"

In [25]:
class(-3.78)

[1] "numeric"

In [26]:
TRUE

[1] TRUE

In [27]:
class(TRUE)

[1] "logical"

In [28]:
class(FALSE)

[1] "logical"

In [29]:
class(TRUE)
T <- 9
class(T)

[1] "logical"

[1] "numeric"

In [30]:
print(4 + 1.2i)

[1] 4+1.2i


In [31]:
class(4 + 1.2i)

[1] "complex"

In [32]:
print("a")

[1] "a"


In [33]:
class("a")

[1] "character"

In [34]:
class("hola")

[1] "character"

In [35]:
class("adios") # Recomendado

[1] "character"

In [36]:
class('adios') # No recomendado

[1] "character"

In [37]:
"hola" y "adios" # Error

ERROR: Error in parse(text = input): <text>:1:8: unexpected symbol
1: "hola" y
           ^


In [39]:
""hola" y "adios"" # Error

ERROR: Error in parse(text = input): <text>:1:3: unexpected symbol
1: ""hola
      ^


In [40]:
'"hola" y "adios"' # Para este tipo de cosas se usan las comillas simples

[1] "\"hola\" y \"adios\""

In [41]:
1 / 0

[1] Inf

In [42]:
1 / Inf

[1] 0

In [43]:
0 / 0

[1] NaN

In [44]:
print(NULL)

NULL


In [45]:
?NULL

NULL                   package:base                    R Documentation

_T_h_e _N_u_l_l _O_b_j_e_c_t

_D_e_s_c_r_i_p_t_i_o_n:

     ‘NULL’ represents the null object in R: it is a reserved word.
     ‘NULL’ is often returned by expressions and functions whose value
     is undefined.

_U_s_a_g_e:

     NULL
     as.null(x, ...)
     is.null(x)
     
_A_r_g_u_m_e_n_t_s:

       x: an object to be tested or coerced.

     ...: ignored.

_D_e_t_a_i_l_s:

     ‘NULL’ can be indexed (see Extract) in just about any
     syntactically legal way: apart from ‘NULL[[]]’ which is an error,
     the result is always ‘NULL’.  Objects with value ‘NULL’ can be
     changed by replacement operators and will be coerced to the type
     of the right-hand side.

     ‘NULL’ is also used as the empty pairlist: see the examples.
     Because pairlists are often promoted to lists, you may encounter
     ‘NULL’ being promoted to an empty list.

     Objects with v

In [46]:
print(NA)

[1] NA


In [47]:
?NA

NA                    package:base                     R Documentation

'_N_o_t _A_v_a_i_l_a_b_l_e' / _M_i_s_s_i_n_g _V_a_l_u_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘NA’ is a logical constant of length 1 which contains a missing
     value indicator.  ‘NA’ can be coerced to any other vector type
     except raw.  There are also constants ‘NA_integer_’, ‘NA_real_’,
     ‘NA_complex_’ and ‘NA_character_’ of the other atomic vector types
     which support missing values: all of these are reserved words in
     the R language.

     The generic function ‘is.na’ indicates which elements are missing.

     The generic function ‘is.na<-’ sets elements to ‘NA’.

     The generic function ‘anyNA’ implements ‘any(is.na(x))’ in a
     possibly faster way (especially for atomic vectors).

_U_s_a_g_e:

     NA
     is.na(x)
     anyNA(x, recursive = FALSE)
     
     ## S3 method for class 'data.frame'
     is.na(x)
     
     is.na(x) <- value
     
_A_r_g_

In [48]:
NaN

[1] NaN

In [49]:
class(NaN)

[1] "numeric"

In [50]:
?NaN

is.finite                 package:base                 R Documentation

_F_i_n_i_t_e, _I_n_f_i_n_i_t_e _a_n_d _N_a_N _N_u_m_b_e_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘is.finite’ and ‘is.infinite’ return a vector of the same length
     as ‘x’, indicating which elements are finite (not infinite and not
     missing) or infinite.

     ‘Inf’ and ‘-Inf’ are positive and negative infinity whereas ‘NaN’
     means ‘Not a Number’.  (These apply to numeric values and real and
     imaginary parts of complex values but not to values of integer
     vectors.)  ‘Inf’ and ‘NaN’ (as well as ‘NA’) are reserved words in
     the R language.

_U_s_a_g_e:

     is.finite(x)
     is.infinite(x)
     is.nan(x)
     
     Inf
     NaN
     
_A_r_g_u_m_e_n_t_s:

       x: R object to be tested: the default methods handle atomic
          vectors.

_D_e_t_a_i_l_s:

     ‘is.finite’ returns a vector of the same length as ‘x’ the j-th
     element of wh

# Operadores aritméticos

In [51]:
1 + 5

[1] 6

In [52]:
5 - 4

[1] 1

In [53]:
3 * 2.1

[1] 6.3

In [54]:
7 / -4.3

[1] -1.627907

In [55]:
2 ^ 3

[1] 8

In [56]:
2 ** -1/2 # Igual que ^

[1] 0.25

In [57]:
4 %% 3

[1] 1

In [58]:
3 %/% 2

[1] 1

# Operadores lógicos

In [59]:
print(1 < 9.5)

[1] TRUE


In [60]:
2.7 <= -5.3

[1] FALSE

In [61]:
4.9 > 2

[1] TRUE

In [62]:
4.9 >= 3

[1] TRUE

In [63]:
5 == 5

[1] TRUE

In [64]:
5 != 5

[1] FALSE

In [65]:
!(5 == 5)

[1] FALSE

In [66]:
(5 == 5) | (5 != 5)

[1] TRUE

In [67]:
(5 == 5) & (5 != 5)

[1] FALSE

In [68]:
1 == TRUE

[1] TRUE

In [69]:
0 == FALSE

[1] TRUE

In [70]:
7 == TRUE

[1] FALSE

In [71]:
as.logical(7) # WTF?

[1] TRUE

# Vectores
La funcion `c()` se usa para crear vectores

In [72]:
c(1,5,8)

[1] 1 5 8

In [73]:
print(c(1,5,8))

[1] 1 5 8


In [74]:
print(c(1,2,3,4,3,5,4,5,2,3,9,-2,5.9,28,44,3,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0))

 [1]  1.0  2.0  3.0  4.0  3.0  5.0  4.0  5.0  2.0  3.0  9.0 -2.0  5.9 28.0 44.0
[16]  3.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0
[31]  9.0  0.0


In [75]:
class(c(1,5,8))

[1] "numeric"

In [76]:
print(c(1.5,5,-8.5,5i))

[1]  1.5+0i  5.0+0i -8.5+0i  0.0+5i


In [77]:
class(c(1.5,5,-8.5,5i))

[1] "complex"

In [78]:
print(c("hola", "adios"))

[1] "hola"  "adios"


In [79]:
print(c("hola", 7))

[1] "hola" "7"   


In [80]:
print(c(TRUE, FALSE, TRUE))

[1]  TRUE FALSE  TRUE


In [81]:
print(c(T, F, T)) # Ojo cuidado!

[1] 9 0 9


In [82]:
print(c(TRUE, 0, TRUE))

[1] 1 0 1


In [83]:
print(as.logical(c(TRUE, 0, TRUE)))

[1]  TRUE FALSE  TRUE


In [84]:
print(as.character(c(3,4,5)))

[1] "3" "4" "5"


In [85]:
is.character(as.character(c(3,4,5)))

[1] TRUE

In [86]:
is.character(c(3,4,5))

[1] FALSE

Se pueden crear vectores dando un rango de valores usando `:`

In [87]:
print(1:4)

[1] 1 2 3 4


In [88]:
print(4:1)

[1] 4 3 2 1


In [89]:
print(1.1:6.9)

[1] 1.1 2.1 3.1 4.1 5.1 6.1


In [90]:
print(-1:5)

[1] -1  0  1  2  3  4  5


In [91]:
vector("numeric", length = 10)

[1] 0 0 0 0 0 0 0 0 0 0

In [92]:
print(vector("numeric", length = 10))

 [1] 0 0 0 0 0 0 0 0 0 0


In [93]:
print(vector("logical", length = 10))

 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE


<i>Atención que se vienen curvas...</i>

In [94]:
print(1:3 + 4:6)

[1] 5 7 9


In [95]:
print(1:3 + 4:7) # Warning! Recycling Rule

Warning message in 1:3 + 4:7:
“longitud de objeto mayor no es múltiplo de la longitud de uno menor”


[1] 5 7 9 8


In [96]:
print(1:3 * 4:6)

[1]  4 10 18


In [97]:
print(1:3 - 4:6)

[1] -3 -3 -3


In [98]:
print(1:3 / 4:6)

[1] 0.25 0.40 0.50


In [99]:
1:3 == 4:6

[1] FALSE FALSE FALSE

In [100]:
1:3 != 4:6

[1] TRUE TRUE TRUE

In [101]:
1:3 < 4:6

[1] TRUE TRUE TRUE

In [102]:
1:3 >= 4:6

[1] FALSE FALSE FALSE

In [103]:
!(0:3)

[1]  TRUE FALSE FALSE FALSE

### WTF? (Falling into the Floating Point Trap)
The R Inferno. Patrick Burns. https://www.burns-stat.com/pages/Tutor/R_inferno.pdf

In [104]:
.1 == (.3 / 3)

[1] FALSE

In [105]:
c(.3, .4 - .1, .5 - .2, .6 - .3, .7 - .4)

[1] 0.3 0.3 0.3 0.3 0.3

In [106]:
unique(c(.3, .4 - .1, .5 - .2, .6 - .3, .7 - .4))

[1] 0.3 0.3 0.3

<i>R is good enough at hiding numerical error that it is easy to forget that it is there. Don’t forget...</i>

In [107]:
1:5-1

[1] 0 1 2 3 4

In [108]:
1:(5-1)

[1] 1 2 3 4

In [109]:
10^2:6

[1] 100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83  82
[20]  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65  64  63
[39]  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47  46  45  44
[58]  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29  28  27  26  25
[77]  24  23  22  21  20  19  18  17  16  15  14  13  12  11  10   9   8   7   6

In [110]:
?Syntax

Syntax                  package:base                   R Documentation

_O_p_e_r_a_t_o_r _S_y_n_t_a_x _a_n_d _P_r_e_c_e_d_e_n_c_e

_D_e_s_c_r_i_p_t_i_o_n:

     Outlines R syntax and gives the precedence of operators.

_D_e_t_a_i_l_s:

     The following unary and binary operators are defined.  They are
     listed in precedence groups, from highest to lowest.

       ‘:: :::’           access variables in a namespace              
       ‘$ @’              component / slot extraction                  
       ‘[ [[’             indexing                                     
       ‘^’                exponentiation (right to left)               
       ‘- +’              unary minus and plus                         
       ‘:’                sequence operator                            
       ‘%any% |>’         special operators (including ‘%%’ and ‘%/%’) 
       ‘* /’              multiply, divide                             
       ‘+ -’   

<i>Paréntesis... usad paréntesis...</i>

# Variables

In [111]:
x <- 1 # A la variable x le asigno 1

In [112]:
print(x)

[1] 1


In [113]:
x = 5 # A la variable x le asigno 1 

In [114]:
print(x)

[1] 5


<b>Atención:</b> `<-` no es lo mismo que `=`

In [115]:
# Do not run!
foo(93, a = 47)
foo(93, a <- 47)

ERROR: Error in foo(93, a = 47): no se pudo encontrar la función "foo"


In [116]:
# Do not run!
system.time(result <- Sys.sleep(5))
result <- system.time(Sys.sleep(5))

   user  system elapsed 
  0.000   0.000   5.002 

Seguimos...

In [117]:
v <- c(2,6,8,10,-2,4.3)
print(v)

[1]  2.0  6.0  8.0 10.0 -2.0  4.3


In [118]:
print(v + 1) # Recycling Rule

[1]  3.0  7.0  9.0 11.0 -1.0  5.3


In [119]:
print(v * v)

[1]   4.00  36.00  64.00 100.00   4.00  18.49


In [120]:
print(v == v)

[1] TRUE TRUE TRUE TRUE TRUE TRUE


In [121]:
all(v == v) # Evalúa si todas las condiciones de un vector lógico son TRUE

[1] TRUE

In [122]:
identical(v,v) # Comprueba si dos objetos son exactamente iguales en tipo, longitud, atributos y valores

[1] TRUE

In [123]:
x <- c(1,1)
y <- c(1,1,1)
all(x == y)
identical(x, y)

Warning message in x == y:
“longitud de objeto mayor no es múltiplo de la longitud de uno menor”


[1] TRUE

[1] FALSE

In [124]:
?`%in%`

match                   package:base                   R Documentation

_V_a_l_u_e _M_a_t_c_h_i_n_g

_D_e_s_c_r_i_p_t_i_o_n:

     ‘match’ returns a vector of the positions of (first) matches of
     its first argument in its second.

     ‘%in%’ is a more intuitive interface as a binary operator, which
     returns a logical vector indicating if there is a match or not for
     its left operand.

_U_s_a_g_e:

     match(x, table, nomatch = NA_integer_, incomparables = NULL)
     
     x %in% table
     
_A_r_g_u_m_e_n_t_s:

       x: vector or ‘NULL’: the values to be matched.  Long vectors are
          supported.

   table: vector or ‘NULL’: the values to be matched against.  Long
          vectors are not supported.

 nomatch: the value to be returned in the case when no match is found.
          Note that it is coerced to ‘integer’.

incomparables: a vector of values that cannot be matched.  Any value in
          ‘x’ matching a value in this 

In [125]:
1:2 %in% 1

[1]  TRUE FALSE

In [126]:
print(v)
print(c(3,2) %in% v)
print(v %in% c(3,2))

[1]  2.0  6.0  8.0 10.0 -2.0  4.3
[1] FALSE  TRUE
[1]  TRUE FALSE FALSE FALSE FALSE FALSE


In [127]:
intersect(c(3,2), v)

[1] 2

In [128]:
print(union(c(3,2), v))

[1]  3.0  2.0  6.0  8.0 10.0 -2.0  4.3


In [129]:
print(union(v, c(3,2)))

[1]  2.0  6.0  8.0 10.0 -2.0  4.3  3.0


In [130]:
print(setdiff(c(3,2), v))

[1] 3


In [131]:
print(setdiff(v, c(3,2)))

[1]  6.0  8.0 10.0 -2.0  4.3


In [132]:
print(setdiff(abs(v), c(3,2)))

[1]  6.0  8.0 10.0  4.3


In [133]:
print(v)
any(v > 2)

[1]  2.0  6.0  8.0 10.0 -2.0  4.3


[1] TRUE

In [134]:
all(v > 2)

[1] FALSE

# Más sobre vectores

In [135]:
print(v)
print(v[1])

[1]  2.0  6.0  8.0 10.0 -2.0  4.3
[1] 2


In [136]:
print(v[0]) # Nada

numeric(0)


In [137]:
print(v[-1])

[1]  6.0  8.0 10.0 -2.0  4.3


In [138]:
print(v)
print(v[-1:-2])

[1]  2.0  6.0  8.0 10.0 -2.0  4.3
[1]  8.0 10.0 -2.0  4.3


In [139]:
print(v[c(1,4)])

[1]  2 10


In [140]:
length(v)

[1] 6

In [141]:
length(4)

[1] 1

In [142]:
length("hola")

[1] 1

In [143]:
nchar("hola") # Más sobre cadenas de caracteres más adelante...

[1] 4

In [144]:
print(v)
v >= 0

[1]  2.0  6.0  8.0 10.0 -2.0  4.3


[1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE

In [145]:
print(v[v >= 0])

[1]  2.0  6.0  8.0 10.0  4.3


In [146]:
print(v[v < 0])

[1] -2


In [147]:
print(v[(v >= 0) & (v <= 5)])

[1] 2.0 4.3


In [148]:
print(v)
v[c(TRUE,FALSE)]

[1]  2.0  6.0  8.0 10.0 -2.0  4.3


[1]  2  8 -2

In [149]:
v[c(-1,-4)]

[1]  6.0  8.0 -2.0  4.3

In [150]:
sum(v)

[1] 28.3

In [151]:
prod(v)

[1] -8256

In [152]:
min(v)

[1] -2

In [153]:
max(v)

[1] 10

In [154]:
w <- c(NULL, 3, NA, 7, NaN)
print(w)
print(class(NaN))
print(class(as.numeric(NA)))

[1]   3  NA   7 NaN
[1] "numeric"
[1] "numeric"


In [155]:
length(w)

[1] 4

In [156]:
class(w)

[1] "numeric"

In [157]:
print(w)
print(sum(w))

[1]   3  NA   7 NaN
[1] NA


In [158]:
sum(w, na.rm = TRUE)

[1] 10

In [159]:
prod(w)

[1] NA

In [160]:
prod(w, na.rm = TRUE)

[1] 21

In [161]:
min(w)

[1] NA

In [162]:
min(w, na.rm = TRUE)

[1] 3

In [163]:
max(w)

[1] NA

In [164]:
max(w, na.rm = TRUE)

[1] 7

In [165]:
print(w)
is.na(w)

[1]   3  NA   7 NaN


[1] FALSE  TRUE FALSE  TRUE

In [166]:
any(is.na(c(1,NA,3)))

[1] TRUE

In [167]:
print(w)
is.nan(w)

[1]   3  NA   7 NaN


[1] FALSE FALSE FALSE  TRUE

Se pueden crear vectores tambien con `seq` o con `rep`

In [168]:
print(1:6)

[1] 1 2 3 4 5 6


In [169]:
?seq

seq                    package:base                    R Documentation

_S_e_q_u_e_n_c_e _G_e_n_e_r_a_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Generate regular sequences.  ‘seq’ is a standard generic with a
     default method.  ‘seq.int’ is a primitive which can be much faster
     but has a few restrictions.  ‘seq_along’ and ‘seq_len’ are very
     fast primitives for two common cases.

_U_s_a_g_e:

     seq(...)
     
     ## Default S3 method:
     seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)),
         length.out = NULL, along.with = NULL, ...)
     
     seq.int(from, to, by, length.out, along.with, ...)
     
     seq_along(along.with)
     seq_len(length.out)
     
_A_r_g_u_m_e_n_t_s:

     ...: arguments passed to or from methods.

from, to: the starting and (maximal) end values of the sequence.  Of
          length ‘1’ unless just ‘from’ is supplied as an unnamed
          argument.

      by: number: increment of the seque

In [170]:
seq(from=12, to=30, by=3)

[1] 12 15 18 21 24 27 30

In [171]:
seq(12, 30, 3) # seq(from=12, to=30, by=3)

[1] 12 15 18 21 24 27 30

In [172]:
seq(-12, 30, 3.4)

[1] -12.0  -8.6  -5.2  -1.8   1.6   5.0   8.4  11.8  15.2  18.6  22.0  25.4
[13]  28.8

In [173]:
seq(1.1, 7, 10)

[1] 1.1

In [174]:
print(seq(1.1, 7, length=10))

 [1] 1.100000 1.755556 2.411111 3.066667 3.722222 4.377778 5.033333 5.688889
 [9] 6.344444 7.000000


In [175]:
seq()

[1] 1

In [176]:
?rep

rep                    package:base                    R Documentation

_R_e_p_l_i_c_a_t_e _E_l_e_m_e_n_t_s _o_f _V_e_c_t_o_r_s _a_n_d _L_i_s_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘rep’ replicates the values in ‘x’.  It is a generic function, and
     the (internal) default method is described here.

     ‘rep.int’ and ‘rep_len’ are faster simplified versions for two
     common cases.  Internally, they are generic, so methods can be
     defined for them (see InternalMethods).

_U_s_a_g_e:

     rep(x, ...)
     
     rep.int(x, times)
     
     rep_len(x, length.out)
     
_A_r_g_u_m_e_n_t_s:

       x: a vector (of any mode including a ‘list’) or a factor or (for
          ‘rep’ only) a ‘POSIXct’ or ‘POSIXlt’ or ‘Date’ object; or an
          S4 object containing such an object.

     ...: further arguments to be passed to or from other methods.  For
          the internal default method these can include:

          ‘times’ a

In [177]:
rep(8,4)

[1] 8 8 8 8

In [178]:
rep(8,4.1) # El entero

[1] 8 8 8 8

In [179]:
print(rep("a",4))

[1] "a" "a" "a" "a"


In [180]:
rep(1:3, 5)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [181]:
length(rep(1:3, 5))

[1] 15

In [182]:
?rep

rep                    package:base                    R Documentation

_R_e_p_l_i_c_a_t_e _E_l_e_m_e_n_t_s _o_f _V_e_c_t_o_r_s _a_n_d _L_i_s_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘rep’ replicates the values in ‘x’.  It is a generic function, and
     the (internal) default method is described here.

     ‘rep.int’ and ‘rep_len’ are faster simplified versions for two
     common cases.  Internally, they are generic, so methods can be
     defined for them (see InternalMethods).

_U_s_a_g_e:

     rep(x, ...)
     
     rep.int(x, times)
     
     rep_len(x, length.out)
     
_A_r_g_u_m_e_n_t_s:

       x: a vector (of any mode including a ‘list’) or a factor or (for
          ‘rep’ only) a ‘POSIXct’ or ‘POSIXlt’ or ‘Date’ object; or an
          S4 object containing such an object.

     ...: further arguments to be passed to or from other methods.  For
          the internal default method these can include:

          ‘times’ a

In [183]:
rep(c(5,12,13), 2)

[1]  5 12 13  5 12 13

In [184]:
rep(c(5,12,13), each=2)

[1]  5  5 12 12 13 13

In [185]:
letters

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [186]:
LETTERS

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [187]:
month.abb

[1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"

In [188]:
month.name

[1] "January"   "February"  "March"     "April"     "May"       "June"     
 [7] "July"      "August"    "September" "October"   "November"  "December"

### WTF?

In [189]:
print(x)
print(x == NA)

[1] 1 1
[1] NA NA


In [190]:
class(x == NA)

[1] "logical"

In [191]:
NA == NA

[1] NA

In [192]:
3 == c(3, 1, 3, NA)

[1]  TRUE FALSE  TRUE    NA

In [193]:
is.na(c(3, 1, 3, NA))

[1] FALSE FALSE FALSE  TRUE

In [194]:
xnotnull <- 42
print(xnotnull == NULL)

logical(0)


In [195]:
xnull <- NULL
print(xnull == NULL)

logical(0)


In [196]:
is.null(xnull)

[1] TRUE

In [197]:
x1 <- 10:1
print(x1)
x1 == c(4, 6)

 [1] 10  9  8  7  6  5  4  3  2  1


[1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

In [198]:
print(x1)
print(x1 == 4)
print(x1 == 6)
print(x1 == 4 | x1 == 6)
print(x1 == 4 & x1 == 6)


 [1] 10  9  8  7  6  5  4  3  2  1
 [1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
 [1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE
 [1] FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE
 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE


In [199]:
print(x1 == 4 | 6)
as.logical(6)

 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE


[1] TRUE

In [200]:
print(x1)
x1 == (4 | 6)

 [1] 10  9  8  7  6  5  4  3  2  1


[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE

In [201]:
4 | 6

[1] TRUE

<i>Esos paréntesis... ¡que no falten!</i>

In [202]:
50 < "7"

[1] TRUE

In [203]:
50 < as.numeric("7")

[1] FALSE

In [204]:
"50" < "7"

[1] TRUE

In [205]:
print(x != 1)
length(x != 1)

[1] FALSE FALSE


[1] 2

In [206]:
length(x) != 1

[1] TRUE

<i>No dejéis que R decida por vosotr@s...</i>

In [207]:
xna <- c(1, NA, 3, 2, 4, 2)
xna

[1]  1 NA  3  2  4  2

In [208]:
print(xna == 2)
xna[xna == 2]

[1] FALSE    NA FALSE  TRUE FALSE  TRUE


[1] NA  2  2

In [209]:
!is.na(xna)

[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE

In [210]:
xna == 2

[1] FALSE    NA FALSE  TRUE FALSE  TRUE

In [211]:
xna[!is.na(xna) & xna == 2] # Analizar!

[1] 2 2

In [212]:
print(xna)
print(!is.na(xna))
print(xna == 2)

[1]  1 NA  3  2  4  2
[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
[1] FALSE    NA FALSE  TRUE FALSE  TRUE


In [213]:
print(xna)
which(xna == 2)

[1]  1 NA  3  2  4  2


[1] 4 6

In [214]:
xna[which(xna == 2)]

[1] 2 2

In [215]:
x4 <- c(a=1, b=2, a=3)
print(x4)

a b a 
1 2 3 


In [216]:
x4["a"]

a 
1

In [217]:
names(x4)

[1] "a" "b" "a"

In [218]:
print(x4[names(x4) %in% "a"])

a a 
1 3 


In [219]:
print(c("missing value"=NA, "real string"="NA"))

missing value   real string 
           NA          "NA" 


### Ejercicios vectores
1) Crea un vector de números impares entre el 1 y el 30 (ambos inclusive)
2) Crea los siguientes vectores:
    * un vector del 1 al 20
    * un vector del 20 al 1
    * un vector que tenga el siguiente patrón 1,2,3,...,19,20,19,18,...,2,1
3) Crea una secuencia de números del 1 al 30 con un incremento de 0.5
4) Crea una secuencia que contenga las cuatro primeras letras del abecedario en minúscula 3 veces cada una (a a a b b b c c c d d d)
5) Crea el vector numérico `x` con los valores 2.3, 3.3, 4.3 y accede al segundo elemento del vector
6) Crea un vector numérico `z` que contenga los números del 1 al 10. Cambia la clase del vector forzando que sea de tipo carácter. Después cambia el vector `z` a numerico otra vez
7) Crea un vector numérico con valores no ordenados usando la función `sample()`. Una vez creado ordena el vector de forma ascendente usando la función `sort()`. ¿Si quisieras invertir el orden de los elementos del vector que función utilizarías?
8) Crea un vector `x` que contenga los elementos -5,-1,0,1,2,3,4,5,6. Escribe un código del tipo `x[algo]`, para extraer:
    * elementos de x menores que 0,
    * elementos de x menores o igual que 0,
    * elementos of x mayor o igual que 3,
    * elementos de x menor que 0 o mayor que 4,
    * elementos de x mayor que 0 y menor que 4,
    * elementos de x distintos de 0
9) Crea los siguientes vectores `x<-month.name[1:6]` y `z<-month.name[4:10]` a partir del vector original `month.name`. Recupera los valores idénticos entre los vectores x y z usando `%in%`
10) R permite extraer elementos de un vector que satisfacen determinadas condiciones usando la función `subset()`. Para el vector x <- c(6,1:3,NA,12) calcula los elementos mayores que 5 en x usando:
     * el filtrado normal, es decir, con el operador `>`
     * la función `subset()`

# Listas

Son estructuras de datos que permiten combinar elementos de diferente tipo y/o tamaño.

In [220]:
list_data <- list("Red", "Green", c(21,32,11), TRUE, 51.23, 119.1i)
print(list_data)

[[1]]
[1] "Red"

[[2]]
[1] "Green"

[[3]]
[1] 21 32 11

[[4]]
[1] TRUE

[[5]]
[1] 51.23

[[6]]
[1] 0+119.1i



In [221]:
class(list_data)

[1] "list"

In [222]:
print(list_data[5:6])

[[1]]
[1] 51.23

[[2]]
[1] 0+119.1i



In [223]:
print(list_data[6])

[[1]]
[1] 0+119.1i



In [224]:
class(list_data[6])

[1] "list"

In [225]:
print(list_data[[6]])

[1] 0+119.1i


In [226]:
class(list_data[[6]])

[1] "complex"

In [227]:
names(list_data) <- c("Colors", "Age", "Time")
print(list_data)

$Colors
[1] "Red"

$Age
[1] "Green"

$Time
[1] 21 32 11

$<NA>
[1] TRUE

$<NA>
[1] 51.23

$<NA>
[1] 0+119.1i



In [228]:
names(list_data) <- c("A", "B", "C", "E", "F", "G")
print(list_data)

$A
[1] "Red"

$B
[1] "Green"

$C
[1] 21 32 11

$E
[1] TRUE

$F
[1] 51.23

$G
[1] 0+119.1i



In [229]:
names(list_data)
attributes(list_data)

[1] "A" "B" "C" "E" "F" "G"

$names
[1] "A" "B" "C" "E" "F" "G"

In [230]:
print(list_data[1])
print(list_data["A"])

$A
[1] "Red"

$A
[1] "Red"



In [231]:
class(list_data["B"])

[1] "list"

In [232]:
list_data[[1]] <- 5

In [233]:
list_data[[1]]

[1] 5

In [234]:
print(list_data)

$A
[1] 5

$B
[1] "Green"

$C
[1] 21 32 11

$E
[1] TRUE

$F
[1] 51.23

$G
[1] 0+119.1i



In [235]:
list_data[["C"]][2] <- "p"

In [236]:
print(list_data)

$A
[1] 5

$B
[1] "Green"

$C
[1] "21" "p"  "11"

$E
[1] TRUE

$F
[1] 51.23

$G
[1] 0+119.1i



In [237]:
print(list_data[1:3])

$A
[1] 5

$B
[1] "Green"

$C
[1] "21" "p"  "11"



In [238]:
print(list_data[c("A","B")])

$A
[1] 5

$B
[1] "Green"



In [239]:
print(list_data)

$A
[1] 5

$B
[1] "Green"

$C
[1] "21" "p"  "11"

$E
[1] TRUE

$F
[1] 51.23

$G
[1] 0+119.1i



In [240]:
print(unlist(list_data))

         A          B         C1         C2         C3          E          F 
       "5"    "Green"       "21"        "p"       "11"     "TRUE"    "51.23" 
         G 
"0+119.1i" 


In [241]:
class(unlist(list_data))

[1] "character"

In [242]:
num_list <- list(1,2,3,4,5)
day_list <- list("Mon","Tue","Wed", "Thurs", "Fri")
new_list <- c(num_list, day_list)
print(new_list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] "Mon"

[[7]]
[1] "Tue"

[[8]]
[1] "Wed"

[[9]]
[1] "Thurs"

[[10]]
[1] "Fri"



In [243]:
new_list[[5]] <- NULL # Borrar opcion 1
print(new_list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] "Mon"

[[6]]
[1] "Tue"

[[7]]
[1] "Wed"

[[8]]
[1] "Thurs"

[[9]]
[1] "Fri"



In [244]:
print(new_list[-5]) # Borrar opcion 2

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] "Tue"

[[6]]
[1] "Wed"

[[7]]
[1] "Thurs"

[[8]]
[1] "Fri"



In [245]:
print(new_list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] "Mon"

[[6]]
[1] "Tue"

[[7]]
[1] "Wed"

[[8]]
[1] "Thurs"

[[9]]
[1] "Fri"



In [246]:
print(list(hola="Hola", 1, 3, adios = 5.6))

$hola
[1] "Hola"

[[2]]
[1] 1

[[3]]
[1] 3

$adios
[1] 5.6



In [247]:
a <- list(hola="Hola", 1, 3, adios = 5.6)
print(a)
print(a[1])
print(a["hola"])
print(a$hola)

$hola
[1] "Hola"

[[2]]
[1] 1

[[3]]
[1] 3

$adios
[1] 5.6

$hola
[1] "Hola"

$hola
[1] "Hola"

[1] "Hola"


In [248]:
a <- list(hola="Hola", 1, 3, adios = 5.6)
a[[1]] <- NULL
print(a)

[[1]]
[1] 1

[[2]]
[1] 3

$adios
[1] 5.6



In [249]:
a[1] <- NULL
print(a)

[[1]]
[1] 3

$adios
[1] 5.6



In [250]:
a[[8]] <- 0
print(a)

[[1]]
[1] 3

$adios
[1] 5.6

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
NULL

[[8]]
[1] 0



In [251]:
a[7] <- list(9)
length(a)
print(a)

[1] 8

[[1]]
[1] 3

$adios
[1] 5.6

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
[1] 9

[[8]]
[1] 0



In [252]:
a[[6]] <- NULL # WTF?
print(a)

[[1]]
[1] 3

$adios
[1] 5.6

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

[[6]]
[1] 9

[[7]]
[1] 0



### Ejercicios listas
1) Crea una lista llamada `mi_lista` que contenga los siguientes elementos: un vector numérico de 15 elementos, un vector de caracteres de 5 elementos y un vector de valores lógicos de 10 elementos todos TRUE
2) Dada la siguiente lista `my_list <- list(name="Fred", wife="Mary", no.children=3, child.ages=c(4,7,9))`:
    * Imprime los nombres de todos los componentes de la lista
    * Devuelve el segundo componente de la lista
    * Recupera el segundo elemento del cuarto componente de la lista 
    * Imprime la longitud del cuarto componente de la lista
    * Reemplaza el cuarto componente de la lista por un vector de 12 numeros del 1 al 12
    * Elimina el componente `wife`
    * Añade un componente más a la lista llamado `pepe`
3) Convertir un vector de 30 números postivos y negativos en una lista con [1ra componente: los 2 primeros elementos, 2da componente: los 5 siguientes pero como caracteres, 3ra componente: los elementos restantes que sean valores positivos, 4ta componente: una lista de caracteres con tu nombre y apellidos (ej: "Rocío" "Romero" "Zaliz")]
    * Una vez creado ponles nombre (ej: "1ro", "2do", etc)
    * Accede al tercer elemento por su nombre
    * Fusiona el primer y cuarto componente en un quinto componente y borra los originales
4) Crea una nueva lista cuyos componentes sean las listas de los ejericios anteriores (OJO: Su longitude debería ser 3)
5) Crea una nueva lista que concatene las listas de los tres primeros ejericios. ¿Qué longitud tiene?

# Matrices

* Las matrices son vectores con un atributo de dimensión. El atributo de dimensión es en sí mismo un vector entero de longitud 2 (nrow, ncol).
* Todas las columnas de una matriz deben tener el mismo tipo (numérico, carácter, etc.) y la misma longitud.

In [253]:
x <- 1:20
print(x)
dim(x) <- c(5,4)
print(x)
attributes(x)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20


$dim
[1] 5 4

In [254]:
x

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [255]:
class(x)

[1] "matrix" "array"

In [256]:
matrix(nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [257]:
matrix(0, nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0

In [258]:
matrix("a", nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] a    a    a   
[2,] a    a    a

In [259]:
matrix(1:10, nrow = 3, ncol = 4)

Warning message in matrix(1:10, nrow = 3, ncol = 4):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8     1  
[3,] 3    6    9     2

In [260]:
matrix(1:10, nrow=3, ncol = 4, byrow=TRUE)

Warning message in matrix(1:10, nrow = 3, ncol = 4, byrow = TRUE):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3] [,4]
[1,] 1     2   3    4   
[2,] 5     6   7    8   
[3,] 9    10   1    2

In [261]:
?matrix

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘matrix’ creates a matrix from the given set of values.

     ‘as.matrix’ attempts to turn its argument into a matrix.

     ‘is.matrix’ tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or ‘expression’
          vector).  Non-atomic classed R objects are coerced by
          ‘as.vector’ and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If ‘FALSE’ (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnam

In [262]:
matrix(1:12, nrow = 3)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [263]:
matrix(1:12, ncol=3)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [264]:
m <- matrix(1.1:12.1, nrow=3, byrow=FALSE)
rownames(m) <- c("A","B","C")
colnames(m) <- c("1","2","x","y")
m

1   2   x   y   
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1

In [265]:
print(dim(m))

[1] 3 4


In [266]:
length(m)

[1] 12

In [267]:
rbind(1:5,11:15)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,] 11   12   13   14   15

In [268]:
cbind(1:5,11:15)

[,1] [,2]
[1,] 1    11  
[2,] 2    12  
[3,] 3    13  
[4,] 4    14  
[5,] 5    15

In [269]:
m

1   2   x   y   
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1

In [270]:
m[1,1]

[1] 1.1

In [271]:
print(m[1,])

   1    2    x    y 
 1.1  4.1  7.1 10.1 


In [272]:
print(m[,1])
print(class(m[,1]))

  A   B   C 
1.1 2.1 3.1 
[1] "numeric"


In [273]:
print(m[,])

    1   2   x    y
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1


In [274]:
print(m[6])

[1] 6.1


In [275]:
print(m)
m[1:2,1:3]

    1   2   x    y
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1


1   2   x  
A 1.1 4.1 7.1
B 2.1 5.1 8.1

In [276]:
m[,c("1", "x")]

1   x  
A 1.1 7.1
B 2.1 8.1
C 3.1 9.1

In [277]:
m[,c(-1,-4)]

2   x  
A 4.1 7.1
B 5.1 8.1
C 6.1 9.1

In [278]:
m[,-"x"] # Error!

ERROR: Error in -"x": argumento no válido para un operador unitario


In [ ]:
print(colnames(m))
c("x") %in% colnames(m) 

[1] "1" "2" "x" "y"


[1] TRUE

In [ ]:
colnames(m) %in% c("x")

[1] FALSE FALSE  TRUE FALSE

In [ ]:
colnames(m)[4] <- "1"
print(colnames(m))

[1] "1" "2" "x" "1"


In [ ]:
m <- m[,!(colnames(m) %in% c("x"))]
m

1   2   1   
A 1.1 4.1 10.1
B 2.1 5.1 11.1
C 3.1 6.1 12.1

In [ ]:
print(m[1,])
class(m[1,])

   1    2    1 
 1.1  4.1 10.1 


[1] "numeric"

In [ ]:
m[1,,drop=FALSE]

1   2   1   
A 1.1 4.1 10.1

In [ ]:
print(m[1,,drop=TRUE])

   1    2    1 
 1.1  4.1 10.1 


In [ ]:
mx <- matrix(1:12, nrow=3, byrow=TRUE)
mx

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [ ]:
mx[3, 2] <- 4
mx

[,1] [,2] [,3] [,4]
[1,] 1    2     3    4  
[2,] 5    6     7    8  
[3,] 9    4    11   12

In [ ]:
mx[2, ] <- c(1,3) # Recycle!
mx

[,1] [,2] [,3] [,4]
[1,] 1    2     3    4  
[2,] 1    3     1    3  
[3,] 9    4    11   12

In [ ]:
print(mx[1:2, 3:4])
mx[1:2, 3:4] <- c(8,4,2,1)
mx

     [,1] [,2]
[1,]    3    4
[2,]    1    3


[,1] [,2] [,3] [,4]
[1,] 1    2     8    2  
[2,] 1    3     4    1  
[3,] 9    4    11   12

In [ ]:
print(dim(mx))

[1] 3 4


In [ ]:
dim(mx)[1]

[1] 3

In [ ]:
dim(mx)[2]

[1] 4

In [ ]:
ncol(mx)

[1] 4

In [ ]:
nrow(mx)

[1] 3

In [ ]:
t(mx)

[,1] [,2] [,3]
[1,] 1    1     9  
[2,] 2    3     4  
[3,] 8    4    11  
[4,] 2    1    12

In [ ]:
diag(mx)

[1]  1  3 11

In [ ]:
m * m

1    2     1     
A 1.21 16.81 102.01
B 4.41 26.01 123.21
C 9.61 37.21 146.41

In [ ]:
m %*% m # Multiplicación de matrices

1     2      1     
A 41.13  87.03 178.83
B 47.43 102.33 212.13
C 53.73 117.63 245.43

In [ ]:
a <- attributes(m)
print(a)

$dim
[1] 3 3

$dimnames
$dimnames[[1]]
[1] "A" "B" "C"

$dimnames[[2]]
[1] "1" "2" "1"




In [ ]:
class(attributes(m))

[1] "list"

In [ ]:
a$dimnames[[1]]

[1] "A" "B" "C"

In [ ]:
print(list_data[[1]][1])

[1] 5


# Arrays

Las matrices con más de dos dimensiones se llaman `array`

In [ ]:
x <- 1:20
dim(x) <- c(2,5,2)
print(x)

, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   11   13   15   17   19
[2,]   12   14   16   18   20



In [ ]:
a <- array(1:24, dim=c(3,4,2))
print(a) # Una matriz de 3 dimensiones

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



In [ ]:
a <- array(1:24, dim=c(3,4,2), 
           dimnames = list(c("ROW1","ROW2","ROW3"), 
                           c("COL1","COL2","COL3","COL4"), 
                           c("Matrix1","Matrix2")))
print(a)

, , Matrix1

     COL1 COL2 COL3 COL4
ROW1    1    4    7   10
ROW2    2    5    8   11
ROW3    3    6    9   12

, , Matrix2

     COL1 COL2 COL3 COL4
ROW1   13   16   19   22
ROW2   14   17   20   23
ROW3   15   18   21   24



In [ ]:
print(a[1,3,,drop=FALSE])

, , Matrix1

     COL3
ROW1    7

, , Matrix2

     COL3
ROW1   19



In [ ]:
a[1,3,1]

[1] 7

In [ ]:
print(a[3,,2])

COL1 COL2 COL3 COL4 
  15   18   21   24 


In [ ]:
print(a[,,2])

     COL1 COL2 COL3 COL4
ROW1   13   16   19   22
ROW2   14   17   20   23
ROW3   15   18   21   24


### Ejercicios matrices y arrays
1) Dada la siguiente matriz:
<pre>laberinto <- matrix(c(
   "O", "X", "O", "O", "O",
   "O", "X", "X", "X", "O",
   "O", "O", "O", "O", "X",
   "X", "X", "X", "O", "X",
   "O", "O", "O", "O", "O"
 ), nrow = 5, byrow = TRUE)</pre>
    * Indique donde están las "X" usando la función `which`
    * Indique donde están las "X" usando la función `which` pero usando el parámetro `arr.ind`
    * Indique cuantos valores "X" hay en la matriz
    * Reemplace las "X" por 1 y los "O" por 0 y convierta la matrix en una matrix numérica
    * Indique si la matrix es simétrica
    * Cree una nueva matrix con los valores en las filas y columnas pares 
2) Crea una matriz que represente un Sudoku. Debe estar inicializada en NA. Luego rellenar solo un 10% de las casillas con un valor entre 1 y 9 (HINT: usa la función `sample`). No se preocupe de que sea un esquema válido (se pueden repetir valores en una fila por ejemplo... eso ya lo haremos más adelante... si acaso...)
3) Teniendo estas dos matrices:
<pre>matriz <- matrix(sample(1:9, 30,replace=TRUE), nrow=5)</pre>
<pre>mascara <- matrix(sample(c(TRUE,FALSE), 30, replace=TRUE), nrow=5)</pre>
    * Aplique la máscara a la matrix, en donde si la posicion en la máscara es FALSE entonces el resultado es 0 y sino se mantiene su valor
    * Calcule el producto de la matriz original por la matriz modificada traspuesta (NOTA: la matriz final será de 5x5)
4) Crea un array 5D llamado "mi_array5D" con las siguientes características, rellénalo con números enteros consecutivos comenzando desde 1:
    - Tamaño de la primera dimensión: 2 elementos
    - Tamaño de la segunda dimensión: 3 elementos
    - Tamaño de la tercera dimensión: 4 elementos
    - Tamaño de la cuarta dimensión: 5 elementos
    - Tamaño de la quinta dimensión: 6 elementos
    
    4.1) Accede a los siguientes elementos del array:
    * los elementos pares (analice la posición de esos valores en las 5 dimensiones)
    * estudiando el caso anterior muestre los elementos impares sin usar ningun tipo de condicional, igualdad o desigualdad
    
    4.2) Redimensiona el array para que tenga:
    - Tamaño de la primera dimensión: 6 elementos.
    - Tamaño de la segunda dimensión: 5 elementos.
    - Tamaño de la tercera dimensión: 4 elementos.
    - Tamaño de la cuarta dimensión: 3 elementos.
    - Tamaño de la quinta dimensión: 2 elementos.
5) Supongamos que tenemos un grafo no dirigido con 6 nodos etiquetados del 1 al 6, y las siguientes aristas:
    * Arista 1: (1, 2)
    * Arista 2: (1, 3)
    * Arista 3: (2, 4)
    * Arista 4: (2, 5)
    * Arista 5: (3, 6)
    * Arista 6: (4, 5)
    
    Crea una matriz de adyacencia "matriz_adyacencia" en R para representar este grafo. En una matriz de adyacencia, las filas y columnas representan los nodos, y un valor 1 indica que existe una arista entre los nodos correspondientes, mientras que un valor 0 indica la ausencia de una arista.
    * Calcula el grado del nodo 4 en el grafo. El grado de un nodo es la cantidad de aristas que inciden en él
    * Encuentra todos los nodos adyacentes del nodo 2
    * Cuenta la cantidad de nodos que tiene una arista hacia si mismos (self-loop)

# Factores (variables nominales)
Los factores son vectores para valores categóricos
* Levels: refers to the input values
* Labels: refers to the output values of the new factor

In [ ]:
Pain <- c(0,3,2,2,1)
Pain

[1] 0 3 2 2 1

In [ ]:
SevPain <- factor(c(0,3,2,2,1), levels=c(0,1,2,3), labels=c("none","mild","medium","severe"))
class(SevPain)

[1] "factor"

In [ ]:
SevPain

[1] none   severe medium medium mild  
Levels: none mild medium severe

In [ ]:
directions <- c("North", "East", "South", "South")
factor(directions)

[1] North East  South South
Levels: East North South

In [ ]:
factor(directions, levels=c("North", "East", "South", "West"), labels=c("N","E","S","W"))

[1] N E S S
Levels: N E S W

In [ ]:
fdir <- factor(directions, levels=c("North", "East", "South", "West"), labels=c("N","E","S","W"))
table(fdir)

fdir
N E S W 
1 1 2 0 

In [ ]:
table(factor(directions))


 East North South 
    1     1     2 

In [ ]:
print(fdir)
fdir[1] <- "E"
print(fdir)
fdir[1] <- "pepe"
print(fdir)

[1] E E S S
Levels: N E S W
[1] E E S S
Levels: N E S W


Warning message in `[<-.factor`(`*tmp*`, 1, value = "pepe"):
“invalid factor level, NA generated”


[1] <NA> E    S    S   
Levels: N E S W


In [ ]:
levels(fdir) <- c(levels(fdir), "pepe")
fdir[1] <- "pepe"
print(fdir)

[1] pepe E    S    S   
Levels: N E S W pepe


# Factores ordenados (variables ordinales)

In [ ]:
status <- c("Lo", "Hi", "Med", "Med", "Hi")
ordered.status <- factor(status, levels=c("Lo", "Med", "Hi"), ordered=TRUE)
print(ordered.status)

[1] Lo  Hi  Med Med Hi 
Levels: Lo < Med < Hi


In [ ]:
table(status)

status
 Hi  Lo Med 
  2   1   2 

In [ ]:
table(ordered.status)

ordered.status
 Lo Med  Hi 
  1   2   2 

 ### WTF?

In [ ]:
f <- factor(c(101,6,8,9,6,103))
print(f)
is.numeric(f)

[1] 101 6   8   9   6   103
Levels: 6 8 9 101 103


[1] FALSE

In [ ]:
as.numeric(f)

[1] 4 1 2 3 1 5

In [ ]:
as.numeric(levels(f))

[1]   6   8   9 101 103

In [ ]:
as.numeric(levels(f))[as.numeric(f)]

[1] 101   6   8   9   6 103

In [ ]:
print(as.character(f))
as.numeric(as.character(f))

[1] "101" "6"   "8"   "9"   "6"   "103"


[1] 101   6   8   9   6 103

In [ ]:
ff <- factor(c("AA", "BA", "CA"))
print(ff)
ff[1:2]

[1] AA BA CA
Levels: AA BA CA


[1] AA BA
Levels: AA BA CA

In [ ]:
ff[1:2, drop=TRUE] # Borrar opcion 1

[1] AA BA
Levels: AA BA

In [ ]:
factor(ff[1:2]) # "Borrar" opcion 2

[1] AA BA
Levels: AA BA

In [ ]:
f1 <- factor(c("AA", "BA", NA, "NA"))
f1

In [ ]:
f1 <- factor(c("AA", "BA", NA, "NA"), exclude=NULL)
f1

### Ejercicios factores
1) Crea un factor llamado "fact_puntuacion" que contenga puntuaciones de 1 al 5 para 1000 productos. Utiliza la función `summary()` para obtener un resumen de la distribución de puntuaciones. ¿Qué puedes deducir del tipo de aleatoriedad usada en `sample`? ¿Es normal, uniforme, ...?
2) Crea un factor ordenado para edades entre 0 y 100 de 100 personas. Utiliza la función `cut` para generar 3 nieveles separados. Ahora reetiqueta el factor como "joven", "adulto" o "anciano". Muestra la frecuencia de cada nivel.
3) Crea un factor para el siguiente vector teniendo en cuenta que los niveles posibles son todas las letras de la "A" a la "Z":
<pre>v <- c("A","I", "I", "J", "A", "Z", "X")</pre>
    * Modifica una de las "I" por una "F"
    * Agrega una nueva "A" en última posición
    * Indica las letras que aparecen en el factor ordenadas por su frecuencia, empezando con la menos frecuente

# Data Frames

Un marco de datos o data frame es una matriz generalizada, donde las diferentes columnas pueden tener diferentes tipos de datos (numérico, carácter, factor, etc.).

Por ejemplo, vectores y/o factores de la misma longitud que están relacionados "transversalmente", de forma que los datos en la misma posición proceden de la misma unidad experimental (sujeto, animal, etc.).

In [ ]:
S <- as.factor(c("F","M","M","F"))
Patients <- data.frame(age=c(31,32,40,50), sex=S)
Patients

age sex
1 31  F  
2 32  M  
3 40  M  
4 50  F

In [ ]:
employee <- c("John Doe","Peter Gynn","Jolie Hope")
salary <- c(21000, 23400, 26800)
startdate <- as.Date(c("2010-11-1","2008-3-25","2007-3-14"))

employ.data <- data.frame(employee, salary, startdate)
employ.data

employee   salary startdate 
1 John Doe   21000  2010-11-01
2 Peter Gynn 23400  2008-03-25
3 Jolie Hope 26800  2007-03-14

In [ ]:
str(employ.data)

'data.frame':	3 obs. of  3 variables:
 $ employee : chr  "John Doe" "Peter Gynn" "Jolie Hope"
 $ salary   : num  21000 23400 26800
 $ startdate: Date, format: "2010-11-01" "2008-03-25" ...


In [ ]:
employ.data <- data.frame(employee, salary, startdate, stringsAsFactors=TRUE)
employ.data

employee   salary startdate 
1 John Doe   21000  2010-11-01
2 Peter Gynn 23400  2008-03-25
3 Jolie Hope 26800  2007-03-14

In [ ]:
ncol(employ.data)

[1] 3

In [ ]:
nrow(employ.data)

[1] 3

In [ ]:
length(employ.data) # ¡Cuidado! -> Nunmero de filas

[1] 3

In [ ]:
summary(employ.data)

       employee     salary        startdate         
 John Doe  :1   Min.   :21000   Min.   :2007-03-14  
 Jolie Hope:1   1st Qu.:22200   1st Qu.:2007-09-18  
 Peter Gynn:1   Median :23400   Median :2008-03-25  
                Mean   :23733   Mean   :2008-10-02  
                3rd Qu.:25100   3rd Qu.:2009-07-13  
                Max.   :26800   Max.   :2010-11-01  

In [ ]:
print(employ.data[,1])
employ.data[1,1]

[1] John Doe   Peter Gynn Jolie Hope
Levels: John Doe Jolie Hope Peter Gynn


[1] John Doe
Levels: John Doe Jolie Hope Peter Gynn

In [ ]:
employ.data[1,]

employee salary startdate 
1 John Doe 21000  2010-11-01

In [ ]:
employ.data[,1]

[1] John Doe   Peter Gynn Jolie Hope
Levels: John Doe Jolie Hope Peter Gynn

In [ ]:
employ.data$employee

[1] John Doe   Peter Gynn Jolie Hope
Levels: John Doe Jolie Hope Peter Gynn

In [ ]:
class(c("John Doe", 50000, "1990-11-1"))

[1] "character"

In [ ]:
rbind(employ.data, c("John Doe", 50000, "1990-11-1"))

employee   salary startdate 
1 John Doe   21000  2010-11-01
2 Peter Gynn 23400  2008-03-25
3 Jolie Hope 26800  2007-03-14
4 John Doe   50000  1990-11-01

In [ ]:
rbind(employ.data, c("Rocio Romero", 50000, "1990-11-1")) # Error

Warning message in `[<-.factor`(`*tmp*`, ri, value = "Rocio Romero"):
“invalid factor level, NA generated”


employee   salary startdate 
1 John Doe   21000  2010-11-01
2 Peter Gynn 23400  2008-03-25
3 Jolie Hope 26800  2007-03-14
4 NA         50000  1990-11-01

In [ ]:
rbind(employ.data, c("John Doe", 50000)) # Error

Warning message in rbind(deparse.level, ...):
“El número de columnas del resultado, 3, no es un múltiplo de la longitud del vector 2 del argumento 2”


ERROR: Error in charToDate(x): la cadena de caracteres no está en un formato estándar inequívoco


In [ ]:
# Crear los datos para el dataframe
year <- c(2000, 2020, 2021, 2021, 2022, 2022, 2023, 2023, 2024, 2024)
country <- c("Argentina", "Brasil", "Chile", "Colombia", "Ecuador", "Perú", "México", "Uruguay", "Paraguay", "Bolivia")
valor1 <- c(100, 120, 90, 110, 80, 105, 115, 95, 125, 75)

# Crear el dataframe
data1 <- data.frame(year, country, valor1)
data1

year country   valor1
1  2000 Argentina 100   
2  2020 Brasil    120   
3  2021 Chile      90   
4  2021 Colombia  110   
5  2022 Ecuador    80   
6  2022 Perú      105   
7  2023 México    115   
8  2023 Uruguay    95   
9  2024 Paraguay  125   
10 2024 Bolivia    75

In [ ]:
# Crear los datos para el dataframe
country <- rep(c("Argentina", "Brasil", "Chile"), each = 1, times = 5)
year <- c(rep(seq(2000, 2006, by = 1), each = 2), 2020)
valor2 <- runif(15, min = 1, max = 100) # Valores aleatorios entre 1 y 100

# Crear el dataframe
data2 <- data.frame(country, year, valor2)
data2

country   year valor2   
1  Argentina 2000 53.864698
2  Brasil    2000 21.550738
3  Chile     2001 56.500270
4  Argentina 2001 40.730196
5  Brasil    2002 61.115564
6  Chile     2002 35.890727
7  Argentina 2003 70.500922
8  Brasil    2003 13.550475
9  Chile     2004  6.381077
10 Argentina 2004 69.496236
11 Brasil    2005 44.924073
12 Chile     2005  9.240742
13 Argentina 2006 19.194801
14 Brasil    2006 34.794244
15 Chile     2020 61.079316

In [ ]:
data1$country <- as.factor(data1$country)
data1

year country   valor1
1  2000 Argentina 100   
2  2020 Brasil    120   
3  2021 Chile      90   
4  2021 Colombia  110   
5  2022 Ecuador    80   
6  2022 Perú      105   
7  2023 México    115   
8  2023 Uruguay    95   
9  2024 Paraguay  125   
10 2024 Bolivia    75

In [ ]:
length(data1)

[1] 3

In [ ]:
levels(data[,2]) <- c(levels(data[,2]), "Corea del Sur")
data[1,2] <- "Corea del Sur"

In [ ]:
levels(data[,2])[length(levels(data[,2])) + 1] <- "Corea del Sur"
data[1,2] <- "Corea del Sur"

In [ ]:
data1[,2] <- list(1:10)
data1

year country valor1
1  2000  1      100   
2  2020  2      120   
3  2021  3       90   
4  2021  4      110   
5  2022  5       80   
6  2022  6      105   
7  2023  7      115   
8  2023  8       95   
9  2024  9      125   
10 2024 10       75

In [ ]:
as.data.frame(as.list(data1))

year country valor1
1  2000  1      100   
2     1  2      120   
3  2021  3       90   
4  2021  4      110   
5  2022  5       80   
6  2022  6      105   
7  2023  7      115   
8  2023  8       95   
9  2024  9      125   
10 2024 10       75

In [ ]:
?merge

merge                   package:base                   R Documentation

_M_e_r_g_e _T_w_o _D_a_t_a _F_r_a_m_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     Merge two data frames by common columns or row names, or do other
     versions of database _join_ operations.

_U_s_a_g_e:

     merge(x, y, ...)
     
     ## Default S3 method:
     merge(x, y, ...)
     
     ## S3 method for class 'data.frame'
     merge(x, y, by = intersect(names(x), names(y)),
           by.x = by, by.y = by, all = FALSE, all.x = all, all.y = all,
           sort = TRUE, suffixes = c(".x",".y"), no.dups = TRUE,
           incomparables = NULL, ...)
     
_A_r_g_u_m_e_n_t_s:

    x, y: data frames, or objects to be coerced to one.

by, by.x, by.y: specifications of the columns used for merging.  See
          ‘Details’.

     all: logical; ‘all = L’ is shorthand for ‘all.x = L’ and ‘all.y =
          L’, where ‘L’ is either ‘TRUE’ or ‘FALSE’.

   all.x: logical; if ‘TRUE’, then ex

In [ ]:
data1

year country   valor1
1  2000 Argentina 100   
2  2020 Brasil    120   
3  2021 Chile      90   
4  2021 Colombia  110   
5  2022 Ecuador    80   
6  2022 Perú      105   
7  2023 México    115   
8  2023 Uruguay    95   
9  2024 Paraguay  125   
10 2024 Bolivia    75

In [ ]:
data2

country   year valor2   
1  Argentina 2000 53.864698
2  Brasil    2000 21.550738
3  Chile     2001 56.500270
4  Argentina 2001 40.730196
5  Brasil    2002 61.115564
6  Chile     2002 35.890727
7  Argentina 2003 70.500922
8  Brasil    2003 13.550475
9  Chile     2004  6.381077
10 Argentina 2004 69.496236
11 Brasil    2005 44.924073
12 Chile     2005  9.240742
13 Argentina 2006 19.194801
14 Brasil    2006 34.794244
15 Chile     2020 61.079316

In [ ]:
merge(data1, data2, by = c("country", "year")) # conserva sólo las observaciones coincidentes

country   year valor1 valor2 
1 Argentina 2000 100    53.8647

In [ ]:
merge(data1, data2, by = c("country", "year"), all.x = TRUE)

country   year valor1 valor2 
1  Argentina 2000 100    53.8647
2  Bolivia   2024  75         NA
3  Brasil    2020 120         NA
4  Chile     2021  90         NA
5  Colombia  2021 110         NA
6  Ecuador   2022  80         NA
7  México    2023 115         NA
8  Paraguay  2024 125         NA
9  Perú      2022 105         NA
10 Uruguay   2023  95         NA

In [ ]:
merge(data1, data2, by = c("country", "year"), all.y = TRUE)

country   year valor1 valor2   
1  Argentina 2000 100    53.864698
2  Argentina 2001  NA    40.730196
3  Argentina 2003  NA    70.500922
4  Argentina 2004  NA    69.496236
5  Argentina 2006  NA    19.194801
6  Brasil    2000  NA    21.550738
7  Brasil    2002  NA    61.115564
8  Brasil    2003  NA    13.550475
9  Brasil    2005  NA    44.924073
10 Brasil    2006  NA    34.794244
11 Chile     2001  NA    56.500270
12 Chile     2002  NA    35.890727
13 Chile     2004  NA     6.381077
14 Chile     2005  NA     9.240742
15 Chile     2020  NA    61.079316

In [ ]:
merge(data1, data2, by = c("country", "year"), all = TRUE)

country   year valor1 valor2   
1  Argentina 2000 100    53.864698
2  Argentina 2001  NA    40.730196
3  Argentina 2003  NA    70.500922
4  Argentina 2004  NA    69.496236
5  Argentina 2006  NA    19.194801
6  Bolivia   2024  75           NA
7  Brasil    2000  NA    21.550738
8  Brasil    2002  NA    61.115564
9  Brasil    2003  NA    13.550475
10 Brasil    2005  NA    44.924073
11 Brasil    2006  NA    34.794244
12 Brasil    2020 120           NA
13 Chile     2001  NA    56.500270
14 Chile     2002  NA    35.890727
15 Chile     2004  NA     6.381077
16 Chile     2005  NA     9.240742
17 Chile     2020  NA    61.079316
18 Chile     2021  90           NA
19 Colombia  2021 110           NA
20 Ecuador   2022  80           NA
21 México    2023 115           NA
22 Paraguay  2024 125           NA
23 Perú      2022 105           NA
24 Uruguay   2023  95           NA

### Ejercicios data frames
1) Usando el dataset `mtcars`:
    * Muestra las 5 primeras filas
    * Presenta un resumen del datasest
    * Haz una copia del dataset y:
        * Convierte la variables "cyl", "gear" y "carb" en factores
        * Convierte las variables "vs" y "am" en lógicas
        * Muestra solo los coches con una potencia ("hp") mayor a 100
        * Crea un nuevo data frame llamado coches_seleccionados que incluya solo las columnas "mpg", "cyl", "hp" y "qsec" del dataset
        * Calcula el resumen estadístico (media, mediana, desviación estándar, etc.) de la columna "mpg" (millas por galón) para todos los coches en el dataset
        * Idem para "cyl" (número de cilindros)
        * Calcula la cantidad total de coches para cada valor único en la columna "cyl" (número de cilindros)
        * Encuentra el modelo de coche con la mayor potencia ("hp") y muestra su información completa
        * Calcula el promedio de potencia de los coches con 8 cilindros
2) Usando el dataset `Cars93` del paquete `MASS` y el dataset `mtcars`:
    * Agrega una columna al dataset de `mtcars` que contenga la marca y modelo de cada coche
    * Combina los dos dataset por modelo y marca del coche solo para aquellos modelos presentes en ambos datasets. ¿Coinciden los demás valores?
3) Supongamos que tienes dos dataframes con información sobre estudiantes de dos cursos diferentes. Cada data frame contiene tres columnas: "Nombre", "Edad" y "Promedio".
<pre>
curso_a <- data.frame(
    Nombre = c("Juan", "María", "Carlos"),
    Edad = c(20, 22, 21),
    Promedio = c(85, 92, 78))
</pre><pre>
curso_b <- data.frame(
       Nombre = c("Ana", "Luis", "Sofía", "Lourdes"),
       Edad = c(19, 23, 20, 21),
       Promedio = c(88, 90, 85, 80))
</pre>
* Combina los dos dataframes en uno solo llamado todos_los_estudiantes
* Agrega una nueva columna llamada "Curso" al dataframe todos_los_estudiantes que indicar a qué curso pertenece cada estudiante ("A" o "B")

In [ ]:
?mtcars

mtcars                package:datasets                 R Documentation

_M_o_t_o_r _T_r_e_n_d _C_a_r _R_o_a_d _T_e_s_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     The data was extracted from the 1974 _Motor Trend_ US magazine,
     and comprises fuel consumption and 10 aspects of automobile design
     and performance for 32 automobiles (1973-74 models).

_U_s_a_g_e:

     mtcars
     
_F_o_r_m_a_t:

     A data frame with 32 observations on 11 (numeric) variables.

       [, 1]  ‘mpg’   Miles/(US) gallon                        
       [, 2]  ‘cyl’   Number of cylinders                      
       [, 3]  ‘disp’  Displacement (cu.in.)                    
       [, 4]  ‘hp’    Gross horsepower                         
       [, 5]  ‘drat’  Rear axle ratio                          
       [, 6]  ‘wt’    Weight (1000 lbs)                        
       [, 7]  ‘qsec’  1/4 mile time                            
       [, 8]  ‘vs’    Engine (0 = V-shaped, 1 = 

In [ ]:
?Cars93

Cars93                  package:MASS                   R Documentation

_D_a_t_a _f_r_o_m _9_3 _C_a_r_s _o_n _S_a_l_e _i_n _t_h_e _U_S_A _i_n _1_9_9_3

_D_e_s_c_r_i_p_t_i_o_n:

     The ‘Cars93’ data frame has 93 rows and 27 columns.

_U_s_a_g_e:

     Cars93
     
_F_o_r_m_a_t:

     This data frame contains the following columns:

     ‘Manufacturer’ Manufacturer.

     ‘Model’ Model.

     ‘Type’ Type: a factor with levels ‘"Small"’, ‘"Sporty"’,
          ‘"Compact"’, ‘"Midsize"’, ‘"Large"’ and ‘"Van"’.

     ‘Min.Price’ Minimum Price (in $1,000): price for a basic version.

     ‘Price’ Midrange Price (in $1,000): average of ‘Min.Price’ and
          ‘Max.Price’.

     ‘Max.Price’ Maximum Price (in $1,000): price for “a premium
          version”.

     ‘MPG.city’ City MPG (miles per US gallon by EPA rating).

     ‘MPG.highway’ Highway MPG.

     ‘AirBags’ Air Bags standard. Factor: none, driver only, or driver
          & pa

In [ ]:
mtcars

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
library(MASS)
Cars93

Manufacturer Model         Type    Min.Price Price Max.Price MPG.city
1  Acura        Integra       Small   12.9      15.9  18.8      25      
2  Acura        Legend        Midsize 29.2      33.9  38.7      18      
3  Audi         90            Compact 25.9      29.1  32.3      20      
4  Audi         100           Midsize 30.8      37.7  44.6      19      
5  BMW          535i          Midsize 23.7      30.0  36.2      22      
6  Buick        Century       Midsize 14.2      15.7  17.3      22      
7  Buick        LeSabre       Large   19.9      20.8  21.7      19      
8  Buick        Roadmaster    Large   22.6      23.7  24.9      16      
9  Buick        Riviera       Midsize 26.3      26.3  26.3      19      
10 Cadillac     DeVille       Large   33.0      34.7  36.3      16      
11 Cadillac     Seville       Midsize 37.5      40.1  42.7      16      
12 Chevrolet    Cavalier      Compact  8.5      13.4  18.3      25      
13 Chevrolet    Corsica       Compact 11.4      11.4  11.4      25      
14 Chevrolet    Camaro        Sporty  13.4      15.1  16.8      19      
15 Chevrolet    Lumina        Midsize 13.4      15.9  18.4      21      
16 Chevrolet    Lumina_APV    Van     14.7      16.3  18.0      18      
17 Chevrolet    Astro         Van     14.7      16.6  18.6      15      
18 Chevrolet    Caprice       Large   18.0      18.8  19.6      17      
19 Chevrolet    Corvette      Sporty  34.6      38.0  41.5      17      
20 Chrylser     Concorde      Large   18.4      18.4  18.4      20      
21 Chrysler     LeBaron       Compact 14.5      15.8  17.1      23      
22 Chrysler     Imperial      Large   29.5      29.5  29.5      20      
23 Dodge        Colt          Small    7.9       9.2  10.6      29      
24 Dodge        Shadow        Small    8.4      11.3  14.2      23      
25 Dodge        Spirit        Compact 11.9      13.3  14.7      22      
26 Dodge        Caravan       Van     13.6      19.0  24.4      17      
27 Dodge        Dynasty       Midsize 14.8      15.6  16.4      21      
28 Dodge        Stealth       Sporty  18.5      25.8  33.1      18      
29 Eagle        Summit        Small    7.9      12.2  16.5      29      
30 Eagle        Vision        Large   17.5      19.3  21.2      20      
⋮  ⋮            ⋮             ⋮       ⋮         ⋮     ⋮         ⋮       
64 Nissan       Sentra        Small    8.7      11.8  14.9      29      
65 Nissan       Altima        Compact 13.0      15.7  18.3      24      
66 Nissan       Quest         Van     16.7      19.1  21.5      17      
67 Nissan       Maxima        Midsize 21.0      21.5  22.0      21      
68 Oldsmobile   Achieva       Compact 13.0      13.5  14.0      24      
69 Oldsmobile   Cutlass_Ciera Midsize 14.2      16.3  18.4      23      
70 Oldsmobile   Silhouette    Van     19.5      19.5  19.5      18      
71 Oldsmobile   Eighty-Eight  Large   19.5      20.7  21.9      19      
72 Plymouth     Laser         Sporty  11.4      14.4  17.4      23      
73 Pontiac      LeMans        Small    8.2       9.0   9.9      31      
74 Pontiac      Sunbird       Compact  9.4      11.1  12.8      23      
75 Pontiac      Firebird      Sporty  14.0      17.7  21.4      19      
76 Pontiac      Grand_Prix    Midsize 15.4      18.5  21.6      19      
77 Pontiac      Bonneville    Large   19.4      24.4  29.4      19      
78 Saab         900           Compact 20.3      28.7  37.1      20      
79 Saturn       SL            Small    9.2      11.1  12.9      28      
80 Subaru       Justy         Small    7.3       8.4   9.5      33      
81 Subaru       Loyale        Small   10.5      10.9  11.3      25      
82 Subaru       Legacy        Compact 16.3      19.5  22.7      23      
83 Suzuki       Swift         Small    7.3       8.6  10.0      39      
84 Toyota       Tercel        Small    7.8       9.8  11.8      32      
85 Toyota       Celica        Sporty  14.2      18.4  22.6      25      
86 Toyota       Camry         Midsize 15.2      18.2  21.2   